### ISSUE TITLE
Open TODO list

### ISSUE THREAD

**Issue by Ebedthan** [Ebedthan/beginR#1]
A collection of tasks to work on and improve beginR. Feel free to tackle any of these if you'd like to pitch in. If there's no name/ID beside a task, it's open :+1:  If there's a name, find that person and ask how to help.

Also, any issue labeled with a green `help` tag is a great place to start collaborating.

## Slides content

- [ ] 0.1-Installer R et Rstudio [Anicet]
- [ ] 0.2-Github pour les utilisateurs de R
- [ ] 0.3-R Markdown

- [ ] 1.1-Qu'est ce que la reproductibilité
- [ ] 1.2-Les outils pour la reproductibilité  
- [ ] 1.3-Les bonnes pratiques dans l'analyse de données  

- [ ] 2.1-La grammaire des graphiques [Anicet]
- [ ] 2.2-Créer des graphiques avec ggplot2 [Anicet]
- [ ] 2.3-Créer des graphiques interactifs [Anicet]

- [ ] 3.1-dplyr: Une grammaire de la manipulation des données
- [ ] 3.2-Manipuler et transformer les données

- [ ] 4.1-Importer et exporter les données des fichiers plats
- [ ] 4.2-Importer et exporter les données des fichiers de logiciels statistiques

- [ ] 5.1-Qu'est ce qu'un modèle?
- [ ] 5.2-Les modèles supervisés
- [ ] 5.3-Les modèles non-supervisés

**Comment by Ebedthan** [comment]
@dickoa do you have some time and can you choose some content to write? thanks.

**Comment by Ebedthan** [comment]
Hello @sbnadejda, this a TODO list for the repo. You can find and choose some content to write by indicating your name after the content :smiley:
